[package]
name = "transmitic_core"
version = "0.10.0"
authors = ["Andrew Shay <andrew.shay@andrewshay.me>"]
edition = "2018"

[lib]
name = "transmitic_core"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.123", features = ["derive", "rc"] }
serde_json = "1.0.61"
rand = "0.8.3"
rand_core = "0.5.1"
aes-gcm = { version = "0.8.0", features = ["heapless"]}
ring = "0.16.20"
base64 = "0.13.0"

[dependencies.x25519-dalek]
version = "1.1.0"