[package]
name = "transmitic_core"
version = "0.11.1"
authors = ["Andrew Shay <andrew.shay@andrewshay.me>"]
edition = "2018"

[lib]
name = "transmitic_core"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.152", features = ["derive", "rc"] }
serde_json = "1.0.91"
rand = "0.8.5"
rand_core = "0.5.1"
aes-gcm = { version = "0.10.1", features = ["heapless"]}
ring = "0.16.20"
base64 = "0.21.0"
crc32fast = "1.3.2"

[dependencies.x25519-dalek]
version = "1.2.0"